### ISSUE TITLE
scenarioNodes palette issue

### ISSUE THREAD

**Issue by hipitihop** [project-alice-assistant/skill_AliceCore#2]
In scenarios Node Red menu "Manage palette" the alicecore shows problem see red exclamation sand poorly formatted output in screenshot:

![image](https://user-images.githubusercontent.com/4626024/75209422-e3327800-57c9-11ea-9d73-361aed31a9f4.png)

**Comment by LazzaAU** [comment]
suggest we can close this one dated feb 25th ?
