### ISSUE TITLE
Question about DND

### ISSUE THREAD

**Issue by poulsp** [project-alice-assistant/skill_AliceCore#8]
I have the main unit without mic snd speaker and DEFAULT_SITE_ID lets say 'default'.
Instead of I have a alice satellite named/DEFAULT_SITE_ID  'default' too
In skill AliceCore I have

```
def stopListenIntent(self, session: DialogSession):
  if session.siteId != constants.DEFAULT_SITE_ID:
    self.notifyDevice(constants.TOPIC_DND, siteId=session.siteId)
  else:
    self.Commons.runRootSystemCommand(['systemctl', 'stop', 'snips-hotword'])

def unmuteSite(self, siteId):
  if siteId != constants.DEFAULT_SITE_ID:
    self.notifyDevice(constants.TOPIC_STOP_DND, siteId=siteId)
  else:
    self.Commons.runRootSystemCommand(['systemctl', 'start', 'snips-hotword'])
```

I miss `self.notifyDevice(constants.TOPIC_DND/TOPIC_STOP_DND, siteId=session.siteId)` in the two 'else:' expressions, for it to work with satellite too.

**Comment by Psychokiller1888** [comment]
You can't have a satellite with the same name as the main unit, Alice doesn't let you do this

**Comment by poulsp** [comment]
yes and it works well

**Comment by Psychokiller1888** [comment]
If you add it manually yes... But adding through device addition intent asks for a room name

**Comment by poulsp** [comment]
I mean that, but i will try, with kitchen for main and ask to add new satellite kitchen.

**Comment by Psychokiller1888** [comment]
no, name your devices according to the room they are placed in. If your main unit is in the office, call it office

**Comment by Psychokiller1888** [comment]
Everything follows that logic, it's the idiom, the way users can ask without specifying room name is based on satellites wearing room names

**Comment by poulsp** [comment]
I know, but then there is a another problem, I have it in dining room, and the spaces gives problems, maybe some snips thing. I just telling that there is some problems. That all.

**Comment by Psychokiller1888** [comment]
what problem with spaces?

**Comment by poulsp** [comment]
It was something with no sounds some times because it say it could not find dining_room with underscore

**Comment by poulsp** [comment]
But i will test it again

**Comment by poulsp** [comment]
Now tested with dining room
DEFAULT_SITE_ID = "default"
Added satellite "dining room"
```
[DeviceManager]  Device with uid d9831a55-669f-4547-b5d1-54404f4d97d2 is not matching its defined room (received dining room but required dining_room
```

In the ProjectAlice system database DeviseManager_devices is room = dining_room
In the satelllites config.py "deviceName": "dining room"

```
[ASRManager]              Capturing what
[ASRManager]              Capturing what's
[ASRManager]              Capturing what time
[ASRManager]              Capturing what time is
[ASRManager]              Capturing what time is it
[ASRManager]              ASR captured: what time is it
[MqttManager]             Using probability threshold of 0.343
[SkillManager]            The intent "GetTime" was consumed by DateDayTimeYear

From snips-watch
[Asr] was asked to stop listening on site dining room
[Asr] captured text "what time is it" in 4.0s
[Asr] was asked to stop listening on site dining room
[AudioServer] was asked to play a wav of 32.7 kB with id 'a8c9471c-6d3d-4f47-aef7-4407621ea931' on site dining room
[VoiceActivity] Up on site dining room
[AudioServer] finished playing wav with id 'a8c9471c-6d3d-4f47-aef7-4407621ea931'
[Nlu] was asked to parse input "what time is it"
[Nlu] detected intent GetTime with confidence score 1.000 for input "what time is it"
[Dialogue] New intent detected GetTime with confidence 1.000
[Dialogue] was ask to end session with id de61538f-df7a-416c-b17c-43d2450d5e40 by saying 'It is 5 16'
[Tts] was asked to say "It is 5 16"
```

There is no sound on the satellite  "dining room"

And you are right can't add a satellite with the same name as the main unit, but the satellite in the same room loses some sounds and voice messages, and it was therefore I got the idea to call (manual inserted) the same name as the main unit. And that worked.

**Comment by Psychokiller1888** [comment]
Mmh, that's because the satellite is declared dining room in snips.toml, where it should be "dining_room". Will add the fix

**Comment by Psychokiller1888** [comment]
It's now fixed on main unit code

**Comment by poulsp** [comment]
It is not quite in place
In the ProjectAlice system database DeviseManager_devices  room  is still = dining_room
[Tts] was asked to say "It is 6 26"
[AudioServer] was asked to play a wav of 60.8 kB with id '8fb7acd8-8aca-46f5-bcdf-3146bb0f620c' on site dining_room

**Comment by Psychokiller1888** [comment]
That's what is meant to be, you cannot use a space in a site id. You gotta change it on your satellite and it'll be ok
